### ISSUE TITLE
Phoenix app without postgres

### ISSUE THREAD

**Issue by jeepers3327** [nickjj/docker-phoenix-example#3]
Hi,

Thank you for creating this awesome boilerplate. I would like to ask if I can use it without postgres.  My reason of excluding postgres is I the data I'm storing are all ephemeral. 

The app I'm building contains frontend (react) and backend (phoenix).
Do I only need to modify the `docker-compose.yml` file?

```
x-app: &default-app
  build:
    context: "."
    target: "${MIX_ENV:-prod}"
    args:
      - "MIX_ENV=${MIX_ENV:-prod}"
      - "NODE_ENV=${NODE_ENV:-production}"
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - "${DOCKER_WEB_VOLUME:-./priv/static:/app/priv/static}"

services:
  web:
    <<: *default-app
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8000/up}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:8000}:8000"

```
